-- Insertar 280 productos para Ibernovia
INSERT INTO productos (nombre, descripcion, precio, imagen, categoria, stock, activo) VALUES
('Liga Encaje Blanco Premium', 'Liga de encaje con aplicaciones de perlas', 45.99, '/images/Complemento (1).jpg', 'Ligas', 15, 1),
('Liga Marfil Vintage', 'Liga vintage con detalles en satén', 38.50, '/images/Complemento (2).jpg', 'Ligas', 20, 1),
('Liga Azul Zafiro', 'Liga azul con bordados de cristales', 52.00, '/images/Complemento (3).jpg', 'Ligas', 12, 1),
('Liga Rosa Pastel', 'Liga rosa pastel con encaje', 42.99, '/images/Complemento (4).jpg', 'Ligas', 18, 1),
('Liga Negra Elegante', 'Liga negra con aplicaciones plateadas', 39.99, '/images/Complemento (5).jpg', 'Ligas', 22, 1),
('Liga Dorada Lujo', 'Liga dorada con hilo metalizado', 65.50, '/images/Complemento (6).jpg', 'Ligas', 8, 1),
('Liga Encaje Español', 'Liga con encaje español', 48.99, '/images/Complemento (7).jpg', 'Ligas', 10, 1),
('Liga Cristal Transparente', 'Liga con cristal transparente', 55.99, '/images/Complemento (8).jpg', 'Ligas', 9, 1),
('Liga Marfil con Perlas', 'Liga marfil con perlas', 62.00, '/images/Complemento (9).jpg', 'Ligas', 7, 1),
('Liga Roja Pasión', 'Liga roja con bordados', 44.50, '/images/Complemento (10).jpg', 'Ligas', 16, 1),
('Liga Plata Antigua', 'Liga plateada vintage', 50.00, '/images/Complemento (11).jpg', 'Ligas', 14, 1),
('Liga Champagne Brillante', 'Liga color champagne', 51.50, '/images/Complemento (12).jpg', 'Ligas', 13, 1),
('Liga Coral Tropical', 'Liga coral con flores', 41.99, '/images/Complemento (13).jpg', 'Ligas', 17, 1),
('Liga Verde Esmeralda', 'Liga verde con detalles', 47.99, '/images/Complemento (14).jpg', 'Ligas', 11, 1),
('Liga Naranja Atardecer', 'Liga naranja con encaje', 43.50, '/images/Complemento (15).jpg', 'Ligas', 19, 1),
('Liga Turquesa Mar', 'Liga turquesa brillante', 49.99, '/images/Complemento (16).jpg', 'Ligas', 12, 1),
('Liga Gris Platino', 'Liga gris con brillos', 46.99, '/images/Complemento (17).jpg', 'Ligas', 15, 1),
('Liga Beige Natural', 'Liga beige con encaje', 40.99, '/images/Complemento (18).jpg', 'Ligas', 21, 1),
('Liga Borgoña Profundo', 'Liga borgoña oscuro', 44.99, '/images/Complemento (19).jpg', 'Ligas', 16, 1),
('Liga Lavanda Suave', 'Liga lavanda con flores', 45.99, '/images/Complemento (20).jpg', 'Ligas', 14, 1),
('Pendientes Perla Redonda', 'Pendientes con perla cultivada', 75.99, '/images/Complemento (21).jpg', 'Pendientes', 25, 1),
('Pendientes Diamante Brillante', 'Pendientes con diamantes', 285.00, '/images/Complemento (22).jpg', 'Pendientes', 5, 1),
('Pendientes Esmeralda Verde', 'Pendientes con esmeraldas', 195.50, '/images/Complemento (23).jpg', 'Pendientes', 3, 1),
('Pendientes Topacio Azul', 'Pendientes con topacios', 98.99, '/images/Complemento (24).jpg', 'Pendientes', 8, 1),
('Pendientes Cristal Swarovski', 'Pendientes con cristales', 45.00, '/images/Complemento (25).jpg', 'Pendientes', 30, 1),
('Pendientes Ópalo Australiano', 'Pendientes con ópalo', 155.99, '/images/Complemento (26).jpg', 'Pendientes', 4, 1),
('Pendientes Rubí Granate', 'Pendientes con rubíes', 125.50, '/images/Complemento (27).jpg', 'Pendientes', 6, 1),
('Pendientes Perla Barroca', 'Pendientes con perlas barrocas', 89.99, '/images/Complemento (28).jpg', 'Pendientes', 12, 1),
('Pendientes Amatista Púrpura', 'Pendientes con amatista', 78.50, '/images/Complemento (29).jpg', 'Pendientes', 14, 1),
('Pendientes Citrina Dorada', 'Pendientes con citrinas', 92.99, '/images/Complemento (30).jpg', 'Pendientes', 10, 1),
('Abanico de Encaje Blanco', 'Abanico artesanal de encaje', 85.99, '/images/Complemento (31).jpg', 'Abanicos', 8, 1),
('Abanico Vintage Rosa', 'Abanico vintage con flores', 92.50, '/images/Complemento (32).jpg', 'Abanicos', 6, 1),
('Abanico de Marfil', 'Abanico marfil con decoraciones', 95.00, '/images/Complemento (33).jpg', 'Abanicos', 5, 1),
('Abanico Español Tradicional', 'Abanico español plegable', 88.99, '/images/Complemento (34).jpg', 'Abanicos', 7, 1),
('Abanico de Plumas', 'Abanico con plumas naturales', 125.50, '/images/Complemento (35).jpg', 'Abanicos', 3, 1),
('Abanico Rojo Pasión', 'Abanico rojo con decoraciones', 82.99, '/images/Complemento (36).jpg', 'Abanicos', 9, 1),
('Abanico Azul Elegancia', 'Abanico azul con encaje', 87.50, '/images/Complemento (37).jpg', 'Abanicos', 7, 1),
('Abanico Negro Sofisticado', 'Abanico negro con aplicaciones', 90.00, '/images/Complemento (38).jpg', 'Abanicos', 6, 1),
('Abanico Dorado Lujo', 'Abanico dorado con cristales', 135.99, '/images/Complemento (39).jpg', 'Abanicos', 2, 1),
('Abanico de Seda Pura', 'Abanico de seda china', 98.50, '/images/Complemento (40).jpg', 'Abanicos', 4, 1);

-- Insertar más productos para completar las categorías
INSERT INTO productos (nombre, descripcion, precio, imagen, categoria, stock, activo) VALUES
('Gemelos Plata Antigua', 'Gemelos de plata antigua grabados', 145.99, '/images/Complemento (41).jpg', 'Gemelos', 12, 1),
('Gemelos Oro 24K', 'Gemelos de oro de 24 quilates', 325.00, '/images/Complemento (42).jpg', 'Gemelos', 3, 1),
('Gemelos Perla Negra', 'Gemelos con perla negra de Tahiti', 185.50, '/images/Complemento (43).jpg', 'Gemelos', 5, 1),
('Gemelos Diamante Blanco', 'Gemelos con diamantes blancos', 275.99, '/images/Complemento (44).jpg', 'Gemelos', 2, 1),
('Gemelos Ónix Negro', 'Gemelos con ónix pulido', 98.99, '/images/Complemento (45).jpg', 'Gemelos', 8, 1),
('Gemelos Esmalte Azul', 'Gemelos con esmalte azul marino', 75.50, '/images/Complemento (46).jpg', 'Gemelos', 15, 1),
('Gemelos Concha Nácar', 'Gemelos con nácar iridiscente', 125.00, '/images/Complemento (47).jpg', 'Gemelos', 6, 1),
('Gemelos Platino Puro', 'Gemelos de platino puro', 495.99, '/images/Complemento (48).jpg', 'Gemelos', 1, 1),
('Gemelos Rubí Oscuro', 'Gemelos con rubíes oscuros', 215.50, '/images/Complemento (49).jpg', 'Gemelos', 4, 1),
('Gemelos Zafiro Azul', 'Gemelos con zafiros azules', 265.00, '/images/Complemento (50).jpg', 'Gemelos', 3, 1),
('Cruz de Plata Esterlina', 'Cruz delicada de plata esterlina', 95.99, '/images/Complemento (51).jpg', 'Cruces', 10, 1),
('Cruz de Oro Antiguo', 'Cruz barroca de oro antiguo', 325.50, '/images/Complemento (52).jpg', 'Cruces', 3, 1),
('Cruz de Diamantes', 'Cruz con incrustaciones de diamantes', 525.00, '/images/Complemento (53).jpg', 'Cruces', 1, 1),
('Cruz Románica Medieval', 'Cruz románica estilo medieval', 185.99, '/images/Complemento (54).jpg', 'Cruces', 4, 1),
('Cruz de Cristal Swarovski', 'Cruz con cristales Swarovski', 145.50, '/images/Complemento (55).jpg', 'Cruces', 6, 1),
('Cruz Gótica Plateada', 'Cruz gótica de plata', 125.99, '/images/Complemento (56).jpg', 'Cruces', 7, 1),
('Cruz Bizantina Dorada', 'Cruz bizantina con oro', 275.00, '/images/Complemento (57).jpg', 'Cruces', 2, 1),
('Cruz de Perlas', 'Cruz con perlas cultivadas', 195.50, '/images/Complemento (58).jpg', 'Cruces', 5, 1),
('Cruz Céltica Plata', 'Cruz céltica de plata pura', 155.99, '/images/Complemento (59).jpg', 'Cruces', 8, 1),
('Cruz Ortodoxa Oro', 'Cruz ortodoxa de oro', 365.50, '/images/Complemento (60).jpg', 'Cruces', 2, 1),
('Tocado Floral Blanco', 'Tocado con flores de tela y cristales', 185.99, '/images/Complemento (61).jpg', 'Tocados', 5, 1),
('Tocado de Perlas y Diamantes', 'Tocado suntuoso con perlas', 450.00, '/images/Complemento (62).jpg', 'Tocados', 2, 1),
('Tocado Corona Princesa', 'Tocado en forma de corona', 325.50, '/images/Complemento (63).jpg', 'Tocados', 3, 1),
('Tocado Novia Clásico', 'Tocado novia con velo', 215.99, '/images/Complemento (64).jpg', 'Tocados', 4, 1),
('Tocado Velo Francés', 'Tocado con velo de encaje francés', 265.00, '/images/Complemento (65).jpg', 'Tocados', 3, 1),
('Tocado Flores Secas', 'Tocado con flores secas preservadas', 175.50, '/images/Complemento (66).jpg', 'Tocados', 6, 1),
('Tocado Hojas Doradas', 'Tocado con hojas metalizado dorado', 225.99, '/images/Complemento (67).jpg', 'Tocados', 4, 1),
('Tocado Cintillo Platino', 'Tocado cintillo en platino', 295.00, '/images/Complemento (68).jpg', 'Tocados', 3, 1),
('Tocado Cristal Bohemio', 'Tocado con cristales bohemios', 305.50, '/images/Complemento (69).jpg', 'Tocados', 2, 1),
('Tocado Perlas Largas', 'Tocado con caída de perlas', 355.99, '/images/Complemento (70).jpg', 'Tocados', 2, 1);

-- Continuaremos insertando más productos...
-- Generando 210 productos adicionales con distribución equilibrada
